--- boxStatus config file
access:
  - ip
  - token
ip_list:
  white_list:
    localhost:    127.0.0.1
    internal:     192.168.0.33
  black_list:
    someone:      123.123.123.1
    someoneelse:  pirateSteve

token:
  saltkey: this is not a secret


